#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "Il manque les noms d'utilisateurs en argument - Fin du script"
    exit 1
fi

for user in "$@"; do
    if id "$user" &>/dev/null; then
        echo "L'utilisateur $user existe déjà"
    else
        useradd "$user"
        if [ "$?" -eq 0 ]; then
            echo "L'utilisateur $user a été créé"
        else
            echo "Erreur à la création de l'utilisateur $user"
        fi
    fi
done
